package com.xigua.miaosha.dataobject;

public class SeckillSuccessDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.seckill_id
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    private Long seckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.user_phone
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    private String userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.seckill_id
     *
     * @return the value of success_killed.seckill_id
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.seckill_id
     *
     * @param seckillId the value for success_killed.seckill_id
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.user_phone
     *
     * @return the value of success_killed.user_phone
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.user_phone
     *
     * @param userPhone the value for success_killed.user_phone
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }
}