package com.xigua.miaosha.dao;

import com.xigua.miaosha.dataobject.SeckillDO;

public interface SeckillDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int deleteByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int insert(SeckillDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int insertSelective(SeckillDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    SeckillDO selectByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int updateByPrimaryKeySelective(SeckillDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int updateByPrimaryKey(SeckillDO record);
}