package com.xigua.miaosha.dao;

import com.xigua.miaosha.dataobject.SeckillSuccessDO;
import com.xigua.miaosha.dataobject.SeckillSuccessDOKey;

public interface SeckillSuccessDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int deleteByPrimaryKey(SeckillSuccessDOKey key);

    /// 通过秒杀库存id删除秒杀成功记录
    int deleteBySeckillId(long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int insert(SeckillSuccessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int insertSelective(SeckillSuccessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    SeckillSuccessDO selectByPrimaryKey(SeckillSuccessDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int updateByPrimaryKeySelective(SeckillSuccessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Thu Mar 21 19:59:09 CST 2019
     */
    int updateByPrimaryKey(SeckillSuccessDO record);
}